trigger:
- main

pool:
  name: 'ubuntu-pfe'  

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - task: UseNode@1
      inputs:
        version: '16.20.1'
      displayName: 'Installer Node.js'

    - script: |
        npm install -g @angular/cli
        npm install
        ng build --prod
      displayName: 'Installer les dépendances et construire l''application'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/dist/demo1' # Assurez-vous que ce chemin est correct en fonction de la configuration de votre angular.json.
        artifactName: 'angular-app'
      displayName: 'Publier l''application Angular'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'angular-app'
        targetPath: '$(Build.ArtifactStagingDirectory)/app'
      displayName: 'Télécharger l''application Angular depuis l''artefact'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'pfe'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az storage blob upload-batch --account-name pfeapp--destination $web --source $(Build.ArtifactStagingDirectory)/app
      displayName: 'Déployer vers Azure Blob Storage'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'  
        artifactName: 'deployment-logs'
      displayName: 'Publier les journaux de déploiement'
